Update CUDA_Build.yaml

diff --git a/.github/workflows/CUDA_Build.yaml b/.github/workflows/CUDA_Build.yaml
--- a/.github/workflows/CUDA_Build.yaml
+++ b/.github/workflows/CUDA_Build.yaml
@@ -59,15 +59,20 @@ jobs:
         with:
           azcliversion: latest
           inlineScript: |
-            echo "Running az aks show command..."
             result=$(az aks show --resource-group my_test --name myAKSCluster --query 'id' 2>&1)
-            echo "Command output: $result"
+            exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              echo "Error executing az aks show command. Exit code: $exit_code"
+              echo "Error message: $result"
+              echo "::error::Error executing az aks show command. Exit code: $exit_code"
+              exit $exit_code
+            fi
+            
             if [[ -z "$result" || "$result" == *"does not exist"* ]]; then
               echo "::set-output name=cluster_exists::false"
             else
               echo "::set-output name=cluster_exists::true"
             fi
-
 
 
    
